### PR TITLE
Fix/event product image

### LINKED ISSUE #271: ERROR AL NO CARGAR IMAGEN DEL PRODUCTO Y EVENTO
**Describe the bug**
al entrar como proveedor y seleccionar un producto notamos que no aparece el logo del producto seleccionado en el formulario de datos 

### Update
This problem is also present in
in editing events. Please solve
**To Reproduce**
entro con credenciales proveedor -selecciono un producto -datos del producto pero no muestra el logo que tiene en la exibision de productos

**Screenshots**

[Screen Recording - Made with FlexClip.webm](https://user-images.githubusercontent.com/111365000/191050394-d4510a9a-ca6a-4c60-890a-367426ce52f6.webm)

# user stori
 como proveedor quiero que el logo del producto al seleccionar el producto se vea en los datos del producto seleccionado

### PR DESCRIPTION
**Pull request by eduardoquispe**
### Description

Please include a summary of the change.

fixes # (issue)

#### Screenshots

If applicable, add screenshots about your changes

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

### CODE REVIEW

File: controllers/events.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ export const getEventsAPI = async (req: NextApiRequest, res: NextApiResponse) =>
 }
 
 export const getEvent = async (
-  eventId: string,
+  eventId: string | string[],
```
Comment (Israel-Laguan) [inline controllers/events.ts:55]: I don't think this sounds correct, @e-azocar @Eghinner please check if this would be an array for an ID

File: controllers/products.ts [hunk 2]
```diff
@@ -15,6 +15,19 @@ interface GetParams {
   query?: string
 }
 
+export const getProduct = async (
+  productId: string | string[],
```
Comment (Israel-Laguan) [inline controllers/products.ts:19]: This seems incorrect

Comment (eduardoquispe) [reply controllers/products.ts:19]: the default typing is as follows

imagen

Comment (eduardoquispe) [reply controllers/products.ts:19]: the id is also sent in this way in product elimination, with this typeface

imagen

Comment (Israel-Laguan) [reply controllers/products.ts:19]: Hmm to me it should be only string

@e-azocar please check

**Comment by angelik0828** [comment]
## ✔️ It was validated and the images previously loaded in the database are loading fine when requesting edition in events and in products.

image
image

**Review by angelik0828 — APPROVED** [review]

File: views/Products/Edit/index.tsx [hunk 3]
```diff
@@ -66,6 +61,20 @@ const EditProductForm: FC<MutableProductFormProps> = ({ onSubmit, originalData,
     }
   }
 
+  useEffect(() => {
+    setValue('description', originalData?.description)
+    setValue('name', originalData?.name)
+    setValue('basePriceSol', originalData?.basePriceSol)
+    if (originalData?.imageUrl) setImageUrl(originalData.imageUrl)
```
Comment (Eghinner) [inline views/Products/Edit/index.tsx:68]: I'm not sure, why not just make this change? Why do you need `getProduct` in `controllers/products.ts`?

Comment (eduardoquispe) [reply views/Products/Edit/index.tsx:68]: @Eghinner to keep saving the imageUrl with the previous url so that it does not upload a new file, it used to happen that I clicked on save and the imageUrl was saved as an empty string because it did not upload a file.

Comment (Eghinner) [reply views/Products/Edit/index.tsx:68]: Yes, you should not upload a new image. And it also caused the empty string problem.
@e-azocar Can you confirm if this is the best way?

File: controllers/events.ts (hunk 1 above)
Comment (Eghinner) [reply controllers/events.ts:55]: I think it is necessary

**Review by Eghinner — APPROVED** [review]

File: views/Products/Edit/index.tsx (hunk 3 above)
Comment (Israel-Laguan) [reply views/Products/Edit/index.tsx:68]: also, add a check, if the imageURL is valid

Comment (Eghinner) [reply views/Products/Edit/index.tsx:68]: this may be another issue
