### PR TITLE
Back button in create event

### LINKED ISSUE #121: CREAR BOTON REGRESAR  / CREATE BACK BUTTON.
PROYECT TASK TEMPLATE.
Crear boton regresar y nombre del evento.

### EXPLANATION

Después de haber ingresado a Evento y seleccionar crear nuevo evento se abre una vista donde se ingresa una información , ya ingresado los datos del evento y seleccionar la opción  Guardar, se abrirá una vista de pantalla con los datos guardados. En la parte superior de la pantalla, se puede ver el botón " Regresar" cuya  función al darle clic sera devolverse a la vista anterior. 
En la parte superior derecha podemos ver el nombre del evento.

After entering Event and selecting create new event, a view opens where information is entered, once the event data has been entered and the Save option is selected, a screen view will open with the saved data. In the upper part of the screen, you can see the "Back" button whose function when clicked is to return to the previous view. 
In the upper right part we can see the name of the event.

### STEPS TO REPRODUCE
1- entro a evento, y selecciono crear nuevo evento.

Image

2- Se habre esta vista igresa la informacion pedida se da en la opción"Guardar
Enter the requested information and click on the "Save" option.

Image

3-Se abre  la siguiente vista
The following view opens

Image

4-Crear el botón "Regresar" y
Create "Back" button
Image

### CHECKLIST

La opción regresar debe estar en la parte superior de la pantalla para regresar  a la vista anterior, ~~el nombre del evento tiene que estar en la parte superior derecha para  saber que evento esta guardado.~~

The back option must be at the top of the screen to return to the previous view, the event name must be at the top right to know which event is saved.

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

### PR DESCRIPTION
**Pull request by PrototypeK02**
Se agrego el boton en el form de crear, se cambio un poco el estilo del logo que no estbaa quedando en linea con la palabra regresar

### CODE REVIEW

File: views/Events/Create/Form.tsx [hunk 1]
```diff
@@ -11,18 +12,21 @@ const CreateEventForm: FC<MutableEventFormProps> = ({ onSubmit, loading }) => {
...
-      <input type="datetime-local" {...register('date', { required: true })} />
-      <input type="file" name="image" accept="image/*" />
-      <select {...register('type', { required: true })}>
-        <option value="ATTENDANCE">Evento</option>
-        <option value="WORKSHOP">Convocatoria</option>
-      </select>
-      <button type="submit">{buttonText}</button>
-    </form>
+    <>
+      <BackHeader parent="" />
```
Comment (Israel-Laguan) [inline views/Events/Create/Form.tsx]: https://github.com/Azordev/did-admin-panel/blob/771e9ce14913f1c163184a4dc232d3041413ce63/pages/productos/crear.tsx#L26

**Comment by angelik0828** [comment]
## ⚠️ the button was created in:

**- Create event:** but it does not have the required styles, it does not go under the create event title, it goes over the word and must be on a white background.

**Current** 

- New event
image

- Event detail
image

**Expected result** 

image


 ## Clicking the blue button brings up this list, the view doesn't exist yet, you could make a blank page and put the return button.

image

image

**Review by e-azocar — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
Tested locally and in deployment

Works as expected

Don't break another implementations
