### PR TITLE
fix: error paginario

### LINKED ISSUE #216: error en paginario
# Describe the bug
Encontramos que en la opción proveedores de did admin panel se ve una lista de proveedores ya ingresados y  el paginador  que informa los proveedores se mueve  al girar el maus , al darle clic ala flecha derecha del paginador para ver mas proveedores agregados no cambia sigue mostrando los mismos

# To Reproduce
--

1. Go to '...'ingreso con usuario y contraseña 
2. Click on '....' pantalla principal (Eventos) 
3. Scroll down to '.... selecciono proveedores'
4. See error se puede notar que al mover maus hacia abajo  también se mueve el paginador , no cambia la informacion al darle clic a la flecha derecha del paginador

# Screenshots

https://user-images.githubusercontent.com/111365000/189997782-d0637629-6dd8-46cd-b377-5a89b02ed8c9.mp4

# Expected behavior
  
El paginador debe quedarse sin movimiento en la parte inferior de la pantalla
 Al darle clic hacis la fecha  derecha debe cambiar los resultados de los proveedores ya que no cambian sigen siendo igual
**Desktop (please complete the following information):**

-

### PR DESCRIPTION
**Pull request by JuanParraIV**
### Description

Please include a summary of the change.

fixes # (#216 )

#### Screenshots

If applicable, add screenshots about your changes

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Comment by Eghinner** [comment]
@angelik0828 Could you compare this one with https://github.com/Azordev/did-admin-panel/pull/220?
And you decide which style should stay

**Review by Eghinner — APPROVED** [review]

File: containers/Proveedores/ProviderContainers.tsx [hunk 1]
```diff
@@ -12,13 +12,17 @@ interface PaginatedSuppliersProps {
 
 const ProviderContainers: FC<PaginatedSuppliersProps> = ({ providers }) => {
   const [CurrentPage, setCurrentPage] = useState(1)
-  const ProvidersPerPage = 3
+  const ProvidersPerPage = 11
```
Comment (Israel-Laguan) [inline containers/Proveedores/ProviderContainers.tsx]: can this be 12?

**Comment by angelik0828** [comment]
## ✔️ This is working correctly the idea is to continue on the page and not to move with the scroll.

image

**Review by angelik0828 — APPROVED** [review]

**Review by Israel-Laguan — APPROVED** [review]
